[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
line-length = 100
src = ["bot_econ", "tests"]

[tool.ruff.lint]
select = ["E", "F", "I", "B", "UP", "ASYNC"]
ignore = ["E203"]

[tool.mypy]
python_version = "3.11"
strict = false
warn_unused_configs = true
warn_unused_ignores = true
plugins = []

[tool.pytest.ini_options]
asyncio_mode = "auto"

